# Generated by Django 4.2 on 2025-01-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_date', models.DateField(auto_now_add=True)),
                ('numbers', models.CharField(max_length=100)),
            ],
        ),
    ]
